#Include 'TopConn.ch'
#Include "tlpp-core.th"

#Define Enter Chr(13) + Chr(10)

#define _rest_oAuth2_secret_ 'secret_do_cliente'
#define _rest_oAuth2_access_expires 3600
#define _rest_oAuth2_refresh_expires 'Date()+1'
#define _rest_oAuth2_client_id 'id_do_cliente'
#define _rest_oAuth2_user 'UserTestDef'
#define _rest_oAuth2_password '123456'


/*/{Protheus.doc} paramsProvider
Função que será utilizada no momento das requisições pelo REST TLPP
@type function
@version V 1.00
@author Edson Hornberger
@since 17/01/2025
/*/
User Function paramsProvider()
 
  local jTlppParams := JSonObject():New()
  local cTlppParams := '{'+;
    '"client_id":"'+_rest_oAuth2_client_id+'",'+;
    '"client_secret":"'+_rest_oAuth2_secret_+'",'+;
    '"username":"'+_rest_oAuth2_user+'",'+;
    '"password":"'+ _rest_oAuth2_password+'",'+;
    '"access_expires":'+cValToChar(_rest_oAuth2_access_expires)+','+;
    '"refresh_expires":"'+_rest_oAuth2_refresh_expires+'",'+;
    '"grant_type" : "password"'+;
    '}'
 
  jTlppParams:fromJson(cTlppParams)
 
Return jTlppParams
